### PR TITLE
docs: add stub framework

### PR DESCRIPTION
**Pull request by jaredallard**
Adds a framework for documentation writing based off of the `mise`[^1]
documentation framework, which I like a lot. Essentially, we are using
`vitepress`[^2] which is just markdown files with some extra features.

[^1]: https://github.com/jdx/mise-docs
[^2]: https://vitepress.dev/

### CODE REVIEW

**Review by deregtd — APPROVED** [review]
I've been combining the build+release tasks since it's almost entirely a c/p, and using if statements for the build, but that's just a nit idea.  But everything else looks good.

**Comment by jaredallard** [comment]
> I've been combining the build+release tasks since it's almost entirely a c/p, and using if statements for the build, but that's just a nit idea. But everything else looks good.

I was thinking about that as well

**Comment by AaronM04** [comment]
@deregtd you might want to consider a closer look at this PR given that the author is implicated in the XZ backdoor stuff: https://boehs.org/node/everything-i-know-about-the-xz-backdoor

**Comment by jaredallard** [comment]
> @deregtd you might want to consider a closer look at this PR given that the author is implicated in the XZ backdoor stuff: [boehs.org/node/everything-i-know-about-the-xz-backdoor](https://boehs.org/node/everything-i-know-about-the-xz-backdoor)

For the record, I've replied on that original PR: https://github.com/jamespfennell/xz/pull/2#issuecomment-2027836356

**Comment by AaronM04** [comment]
> > @deregtd you might want to consider a closer look at this PR given that the author is implicated in the XZ backdoor stuff: [boehs.org/node/everything-i-know-about-the-xz-backdoor](https://boehs.org/node/everything-i-know-about-the-xz-backdoor)
> 
> For the record, I've replied on that original PR: [jamespfennell/xz#2 (comment)](https://github.com/jamespfennell/xz/pull/2#issuecomment-2027836356)

OK so it seems like you innocently picked the latest version of xz there. It was unfortunate timing that you did that in between the backdoor release and its discovery. Sorry about the "implicated" label...

**Pull request merged**
